apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: dfb5s9mkiv5kwf
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: homeside
      defaultBucket: heating
    secureJsonData:
      token: $INFLUXDB_TOKEN

  - name: Svenskeb API
    type: yesoreyeram-infinity-datasource
    uid: svenskeb-api
    access: proxy
    jsonData:
      # Base URL for the web app (host machine IP)
      url: http://192.168.86.9:5000
