apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: dfb5s9mkiv5kwf
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: homeside
      defaultBucket: heating
    secureJsonData:
      token: homeside_token_2026_secret
